[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[build.production]
  BASE_URL = "https://musical-snickerdoodle-afc0db.netlify.app"
  PORT = "3000"

[context.development]
  BASE_URL = "http://localhost:3000"
  PORT = "3000"
